Check for Kerberos ticket before starting EG

diff --git a/roles/notebook/templates/start-elyra.sh.j2 b/roles/notebook/templates/start-elyra.sh.j2
--- a/roles/notebook/templates/start-elyra.sh.j2
+++ b/roles/notebook/templates/start-elyra.sh.j2
@@ -9,6 +9,14 @@ if [ "$(whoami)" != "{{ notebook.user }}" ]; then
         exit -1
 fi
 
+{% if notebook.enable_kerberos == true %}
+if ! klist -s
+then
+    echo "INVALID Kerberos ticket; please run kinit"
+    exit 1
+fi
+{% endif %}
+
 unset XDG_RUNTIME_DIR
 export EG_REMOTE_HOSTS={{ hostvars.values()|map(attribute='inventory_hostname')|join(',') }}
 export EG_REMOTE_USER={{ notebook.user }}
